no_color = false
gitignore = false
hgignore = false
dockerignore = false
is_zip_archive = [
    ".zip",
    ".jar",
    ".war",
    ".ear",
]
is_archive = [
    ".7z",
    ".bz2",
    ".bzip2",
    ".gz",
    ".gzip",
    ".lz",
    ".rar",
    ".tar",
    ".xz",
    ".zip",
]
is_audio = [
    ".aac",
    ".aiff",
    ".amr",
    ".flac",
    ".gsm",
    ".m4a",
    ".m4b",
    ".m4p",
    ".mp3",
    ".ogg",
    ".wav",
    ".wma",
]
is_book = [
    ".azw3",
    ".chm",
    ".djv",
    ".djvu",
    ".epub",
    ".fb2",
    ".mobi",
    ".pdf",
]
is_doc = [
    ".accdb",
    ".doc",
    ".docm",
    ".docx",
    ".dot",
    ".dotm",
    ".dotx",
    ".mdb",
    ".odp",
    ".ods",
    ".odt",
    ".pdf",
    ".potm",
    ".potx",
    ".ppt",
    ".pptm",
    ".pptx",
    ".rtf",
    ".xlm",
    ".xls",
    ".xlsm",
    ".xlsx",
    ".xlt",
    ".xltm",
    ".xltx",
    ".xps",
]
is_font = [
    ".eot",
    ".fon",
    ".otc",
    ".otf",
    ".ttc",
    ".ttf",
    ".woff",
    ".woff2",
]
is_image = [
    ".bmp",
    ".exr",
    ".gif",
    ".heic",
    ".jpeg",
    ".jpg",
    ".jxl",
    ".png",
    ".psb",
    ".psd",
    ".svg",
    ".tga",
    ".tiff",
    ".webp",
]
is_source = [
    ".asm",
    ".bas",
    ".c",
    ".cc",
    ".ceylon",
    ".clj",
    ".coffee",
    ".cpp",
    ".cs",
    ".d",
    ".dart",
    ".elm",
    ".erl",
    ".go",
    ".gradle",
    ".groovy",
    ".h",
    ".hh",
    ".hpp",
    ".java",
    ".jl",
    ".js",
    ".jsp",
    ".jsx",
    ".kt",
    ".kts",
    ".lua",
    ".nim",
    ".pas",
    ".php",
    ".pl",
    ".pm",
    ".py",
    ".rb",
    ".rs",
    ".scala",
    ".sol",
    ".swift",
    ".tcl",
    ".ts",
    ".tsx",
    ".vala",
    ".vb",
    ".zig",
]
is_video = [
    ".3gp",
    ".avi",
    ".flv",
    ".m4p",
    ".m4v",
    ".mkv",
    ".mov",
    ".mp4",
    ".mpeg",
    ".mpg",
    ".webm",
    ".wmv",
]
default_file_size_format = ""
check_for_updates = false
