[window]
opacity = 0.95
padding = { x = 5, y = 3 }

[font]
size = 10

[bell]
duration = 1

[terminal]
osc52 = "CopyPaste"

[general]
import = [
    "~/.config/alacritty/colors.toml",
    ]

### Here starts alacritty colors

### Here ends alacritty colors
