color_fg0 = '#cbd1d8'
color_bg1 = '#20282f'
color_bg3 = '#697077'
color_blue = '#526480'
color_aqua = '#5bb3c4'
color_green = '#497e26'
color_orange = '#ae6858'
color_purple = 'purple'
color_red = '#a44c3b'
color_yellow = '#ad9b7f'
