color_fg0 = '#d3ccc3'
color_bg1 = '#4c111b'
color_bg3 = '#856163'
color_blue = '#1137a4'
color_aqua = '#20c0f4'
color_green = '#10ac6a'
color_orange = '#bd955f'
color_purple = 'purple'
color_red = '#b08957'
color_yellow = '#eec85b'
