color_fg0 = '#cedadb'
color_bg1 = '#0f3c3c'
color_bg3 = '#607f80'
color_blue = '#65a0d2'
color_aqua = '#50b3e2'
color_green = '#25a36e'
color_orange = '#ae4e1e'
color_purple = 'purple'
color_red = '#af4c1d'
color_yellow = '#9a5f2d'
