color_fg0 = '#d4cac4'
color_bg1 = '#1a273f'
color_bg3 = '#696c78'
color_blue = '#0b27e8'
color_aqua = '#3cd4bf'
color_green = '#2fcb6a'
color_orange = '#d88c30'
color_purple = 'purple'
color_red = '#ff0000'
color_yellow = '#dab83b'
