color_fg0 = '#d3d9df'
color_bg1 = '#17235c'
color_bg3 = '#677194'
color_blue = '#0911d6'
color_aqua = '#00feff'
color_green = '#00ff00'
color_orange = '#ffa400'
color_purple = 'purple'
color_red = '#cf0818'
color_yellow = '#f9fc00'
