color_fg0 = '#dae0d5'
color_bg1 = '#1c2a22'
color_bg3 = '#6d786e'
color_blue = '#45223e'
color_aqua = '#68b19d'
color_green = '#67b09c'
color_orange = '#984f63'
color_purple = 'purple'
color_red = '#974e62'
color_yellow = '#baddc1'
