color_fg0 = '#dedfd4'
color_bg1 = '#1f243d'
color_bg3 = '#70747d'
color_blue = '#101dc5'
color_aqua = '#4ebcc3'
color_green = '#179d8b'
color_orange = '#cea355'
color_purple = 'purple'
color_red = '#b1433c'
color_yellow = '#d4b65b'
