color_fg0 = '#cddad9'
color_bg1 = '#1c2831'
color_bg3 = '#677479'
color_blue = '#2e4bba'
color_aqua = '#93d9c8'
color_green = '#3d6a52'
color_orange = '#e38324'
color_purple = 'purple'
color_red = '#ff0509'
color_yellow = '#d1b445'
