color_fg0 = '#f6f6f4'
color_bg1 = '#2c261e'
color_bg3 = '#827f79'
color_blue = '#1e3caa'
color_aqua = '#5fb2df'
color_green = '#325266'
color_orange = '#62809a'
color_purple = 'purple'
color_red = '#a04d20'
color_yellow = '#e1c355'
