color_fg0 = '#d8d2ca'
color_bg1 = '#2b2524'
color_bg3 = '#756f6b'
color_blue = '#093ed4'
color_aqua = '#36aad7'
color_green = '#3fae75'
color_orange = '#f67c26'
color_purple = 'purple'
color_red = '#c95528'
color_yellow = '#f7b74d'
