color_fg0 = '#c7c7b3'
color_bg1 = '#351f0d'
color_bg3 = '#736754'
color_blue = '#0541cf'
color_aqua = '#03b6cc'
color_green = '#2b7963'
color_orange = '#f4831c'
color_purple = 'purple'
color_red = '#fc4c34'
color_yellow = '#7c5067'
