color_fg0 = '#c7c9b5'
color_bg1 = '#22291a'
color_bg3 = '#686d5c'
color_blue = '#4d4880'
color_aqua = '#8585c3'
color_green = '#61733f'
color_orange = '#928f58'
color_purple = 'purple'
color_red = '#7a7a3c'
color_yellow = '#b2b77f'
