color_fg0 = '#e6ebe4'
color_bg1 = '#1e2833'
color_bg3 = '#737b7e'
color_blue = '#080ff5'
color_aqua = '#37c2eb'
color_green = '#4e973e'
color_orange = '#f1a42e'
color_purple = 'purple'
color_red = '#ce482d'
color_yellow = '#ffd04e'
