color_fg0 = '#dae3e1'
color_bg1 = '#272726'
color_bg3 = '#737776'
color_blue = '#155696'
color_aqua = '#61cbd2'
color_green = '#407655'
color_orange = '#e1875a'
color_purple = 'purple'
color_red = '#9e342d'
color_yellow = '#eaa969'
