color_fg0 = '#d1d3dd'
color_bg1 = '#1f1d60'
color_bg3 = '#6b6b95'
color_blue = '#454652'
color_aqua = '#3ab0c7'
color_green = '#33b846'
color_orange = '#eaa334'
color_purple = 'purple'
color_red = '#c54f38'
color_yellow = '#eacc49'
