color_fg0 = '#dcd0d6'
color_bg1 = '#441a11'
color_bg3 = '#856865'
color_blue = '#0539b7'
color_aqua = '#12b5ae'
color_green = '#238474'
color_orange = '#a1683e'
color_purple = 'purple'
color_red = '#ed4a51'
color_yellow = '#a06a3f'
