color_fg0 = '#dde4e6'
color_bg1 = '#1c2548'
color_bg3 = '#6e768b'
color_blue = '#0927c3'
color_aqua = '#1bbcb6'
color_green = '#2c9c69'
color_orange = '#e88e3f'
color_purple = 'purple'
color_red = '#e1211b'
color_yellow = '#e2a947'
