color_fg0 = '#c0cfcf'
color_bg1 = '#252729'
color_bg3 = '#676f70'
color_blue = '#0a676c'
color_aqua = '#4dc2be'
color_green = '#098379'
color_orange = '#d76e67'
color_purple = 'purple'
color_red = '#b23d41'
color_yellow = '#f59893'
