color_fg0 = '#c8c8f2'
color_bg1 = '#1a273a'
color_bg3 = '#646c88'
color_blue = '#4674ad'
color_aqua = '#5294e2'
color_green = '#3f4551'
color_orange = '#b1742c'
color_purple = 'purple'
color_red = '#ad6b1d'
color_yellow = '#b98b52'
