color_fg0 = '#dbc8b8'
color_bg1 = '#182835'
color_bg3 = '#6b6c6d'
color_blue = '#4f74b2'
color_aqua = '#549dc7'
color_green = '#2c7e68'
color_orange = '#b87f4c'
color_purple = 'purple'
color_red = '#ab6238'
color_yellow = '#b08b4d'
