color_fg0 = '#dedbd3'
color_bg1 = '#172838'
color_bg3 = '#6c747a'
color_blue = '#0c3e9c'
color_aqua = '#1bc7f9'
color_green = '#08785b'
color_orange = '#c39a6b'
color_purple = 'purple'
color_red = '#723a32'
color_yellow = '#f3c163'
