color_fg0 = '#c2c7b3'
color_bg1 = '#0c2031'
color_bg3 = '#5a6768'
color_blue = '#0100b2'
color_aqua = '#6f7e9d'
color_green = '#00ac67'
color_orange = '#e87e43'
color_purple = 'purple'
color_red = '#ff0001'
color_yellow = '#ffb568'
