color_fg0 = '#cccdcd'
color_bg1 = '#1f2926'
color_bg3 = '#696f6d'
color_blue = '#375e9e'
color_aqua = '#629bc6'
color_green = '#668451'
color_orange = '#c18f52'
color_purple = 'purple'
color_red = '#9d6439'
color_yellow = '#c8a161'
