color_fg0 = '#e0e4da'
color_bg1 = '#391f28'
color_bg3 = '#807374'
color_blue = '#11589f'
color_aqua = '#19eff7'
color_green = '#4f7f54'
color_orange = '#d58f4b'
color_purple = 'purple'
color_red = '#9d4c2e'
color_yellow = '#eea760'
