icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome6"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

# [[block]]
# block = "focused_window"
# [block.format]
# full = " $title |"
# short = " $title.str(max_w:20) |"

# [[block]]
# block = "weather"
# format = " $icon $weather ($location) $temp, $wind m/s $direction "
# format_alt = " $icon_ffin Forecast (9 hour avg) {$temp_favg ({$temp_fmin}-{$temp_fmax})|Unavailable} "
# [block.service]
# name = "openweathermap"
# api_key = "XXX"
# city_id = "5398563"
# units = "metric"
# forecast_hours = 9

# [[block]]
# block = "custom"
# command = "sed 's/  //' <(curl 'https://wttr.in/?format=1' -s)"
# interval = 600

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
#format = " $icon $mem_total_used_percents.eng(w:2) "
#format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
warning_mem = 70
critical_mem = 90

#
# [[block]]
# block = "disk_space"
# path = "/"
# info_type = "available"
# alert_unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0
# format = " $icon root: $available.eng(w:2) "

[[block]]
block = "notify"
driver = "swaync"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"

# [[block]]
# block = "scratchpad"

[[block]]
block = "net"
format = " $icon $signal_strength "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "keyboard_layout"
driver = "sway"
interval = 15
format = " $layout "
[block.mappings]
"English (US)" = "US"
"French" = "FR"
"Arabic" = "AR"

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%a %d/%m')"

[[block]]
block = "time"
interval = 5
format = "<b>$timestamp.datetime(f:'%R')</b> "
