# Global settings
shell = "bash -c '{}'"
# default-scheme = "base16-mocha"
#hooks = [ "command1", "command2" ]

# Item configurations
[[items]]
name = "tinted-shell"
path = "~/.local/share/tinted-theming/tinty/repos/tinted-shell"
themes-dir = "scripts"
hook = "source %f"
supported-systems = ["base16"]

[[items]]
name = "base16-css"
path = "~/.local/share/tinted-theming/tinty/repos/base16-css"
themes-dir = "colors"
hook = "cp -r %f ~/.config/colors/colors.css"
supported-systems = ["base16", "base24"]

# [[items]]
# name = "base16-ironbar"
# path = "~/.local/share/tinted-theming/tinty/repos/base16-ironbar"
# themes-dir = "themes"
# hook = "cp -r %f ~/.config/ironbar/colors.css; ironbar load-css ~/.config/ironbar/style.css"
# supported-systems = ["base16"]

[[items]]
name = "base16-albert"
path = "~/.local/share/tinted-theming/tinty/repos/base16-albert"
themes-dir = "themes"
hook = "cp -r %f '~/.local/share/albert/widgetsboxmodel/themes/Tinted Spotlight Dark.qss'"
supported-systems = ["base16"]

[[items]]
name = "base16-rofi"
path = "~/.local/share/tinted-theming/tinty/repos/base16-rofi"
themes-dir = "colors"
hook = "cp -r %f ~/.config/rofi/colors.rasi"

# [[items]]
# name = "base16-anyrun"
# path = "~/.local/share/tinted-theming/tinty/repos/base16-anyrun"
# themes-dir = "themes"
# hook = "cp -r %f ~/.config/anyrun/colors.css"
# supported-systems = ["base16"]

# [[items]]
# name = "base16-onagre"
# path = "~/.local/share/tinted-theming/tinty/repos/base16-onagre"
# themes-dir = "themes"
# hook = "cp -r %f ~/.config/onagre/tinted.scss"
# supported-systems = ["base16"]

[[items]]
name = "base16-fzf"
path = "~/.local/share/tinted-theming/tinty/repos/base16-fzf"
themes-dir = "bash"
hook = "cp -r %f ~/.fzfcolors.sh && source ~/.fzfcolors.sh"
supported-systems = ["base16"]

# [[items]]
# name = "base16-sweep"
# path = "~/.local/share/tinted-theming/tinty/repos/base16-sweep"
# themes-dir = "themes"
# hook = "cp -r %f ~/.sweep.sh && source ~/.sweep.sh"
# supported-systems = ["base16"]

[[items]]
name = "base16-kitty"
path = "~/.local/share/tinted-theming/tinty/repos/base16-kitty"
themes-dir = "colors"
hook = "cp -r %f ~/.config/kitty/tinted.conf"
supported-systems = ["base16"]

# [[items]]
# name = "base16-alacritty"
# path = "~/.local/share/tinted-theming/tinty/repos/base16-alacritty"
# themes-dir = "colors"
# hook = "cp -r %f ~/.config/alacritty/colors.toml"
# supported-systems = ["base16"]

# [[items]]
# name = "base16-konsole"
# path = "~/.local/share/tinted-theming/tinty/repos/base16-konsole"
# themes-dir = "colorscheme"
# hook = "cp -r %f ~/.local/share/konsole/mykonsole.colorscheme"
# supported-systems = ["base16"]

[[items]]
name = "base16-helix"
path = "~/.local/share/tinted-theming/tinty/repos/base16-helix"
themes-dir = "themes"
hook = "cp -r %f ~/.config/helix/themes/tinted-helix.toml"
supported-systems = ["base16"]

## using flavours to config other tools
[[items]]
name = "base16-flavours"
path = "~/.local/share/tinted-theming/tinty/repos/base16-flavours"
themes-dir = "colors"
hook = "cp -r %f ~/.local/share/flavours/base16/schemes/generated/"
supported-systems = ["base16"]
## end flavours


[[items]]
name = "base16-hyprland"
path = "~/.local/share/tinted-theming/tinty/repos/base16-hyprland"
themes-dir = "colors"
hook = "cp -r %f ~/.config/hypr/colors.conf"
supported-systems = ["base16"]

[[items]]
name = "base16-labwc"
path = "~/.local/share/tinted-theming/tinty/repos/base16-labwc"
themes-dir = "colors"
hook = "cp -r %f ~/.local/share/themes/breeze-dark-ob-tinted/openbox-3/themerc && labwc -r"
supported-systems = ["base16"]

# [[items]]
# name = "base16-sway"
# path = "~/.local/share/tinted-theming/tinty/repos/base16-sway"
# themes-dir = "themes"
# hook = "cp -r %f ~/.config/sway/config.d/colors.conf && swaymsg reload"
# supported-systems = ["base16"]

# [[items]]
# name = "base16-swaylock"
# path = '~/.local/share/tinted-theming/tinty/repos/base16-swaylock'
# themes-dir = 'colors'
# hook = "sed -i '/^# TINTY START$/,/^# TINTY END$/{//!d}' ~/.config/swaylock/config && sed -i '/^# TINTY START$/r %f' ~/.config/swaylock/config"
# supported-systems = ["base16"]
#
#
# [[items]]
# name = 'base16-starship'
# path = '~/.local/share/tinted-theming/tinty/repos/base16-starship'
# themes-dir = 'colors'
# hook = "sed -i '/^# TINTY START$/,/^# TINTY END$/{//!d}' ~/.config/starship.toml && sed -i '/^# TINTY START$/r %f' ~/.config/starship.toml"
# supported-systems = ["base16"]
