#!/usr/bin/env bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="eww -c $HOME/.config/eww/so"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	if [[ -f "$FILE" ]]; then
		rm "$FILE"
	fi
	${EWW} --force-wayland daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open yikhbar
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} close-all && ${EWW} kill
	rm "$FILE"
fi
