
[[end]]
class = "power-menu"
tooltip = "Up: {{30000:uptime | cut -d',' -f1 | cut -d' ' -f5-}}"
type = "custom"

[[end.bar]]
label = ""
name = "power-btn"
on_click = "popup:toggle"
type = "button"

[[end.popup]]
orientation = "vertical"
type = "box"

[[end.popup.widgets]]
label = "Power menu"
name = "header"
type = "label"

[[end.popup.widgets]]
type = "box"

[[end.popup.widgets.widgets]]
class = "power-btn"
label = "<span font-size='20pt'></span>"
on_click = "!so-confirm-logout-yad.sh lock"
tooltip = "Lock screen"
type = "button"

[[end.popup.widgets.widgets]]
class = "power-btn"
label = "<span font-size='20pt'>󰬩</span>"
on_click = "!so-confirm-logout-yad.sh logout"
tooltip = "Log out"
type = "button"

[[end.popup.widgets.widgets]]
class = "power-btn"
label = "<span font-size='20pt'></span>"
on_click = "!so-confirm-logout-yad.sh hibernate"
tooltip = "Hibernate"
type = "button"

[[end.popup.widgets.widgets]]
class = "power-btn"
label = "<span font-size='20pt'></span>"
on_click = "!so-confirm-logout-yad.sh suspend"
tooltip = "Suspend"
type = "button"

[[end.popup.widgets.widgets]]
class = "power-btn"
label = "<span font-size='20pt'></span>"
tooltip = "Restart"
on_click = "!so-confirm-logout-yad.sh reboot"
type = "button"

[[end.popup.widgets.widgets]]
class = "power-btn"
label = "<span font-size='20pt'></span>"
on_click = "!so-confirm-logout-yad.sh shutdown"
tooltip = "Shutdown"
type = "button"

[[end.popup.widgets]]
label = "\nUptime: {{30000:uptime | cut -d',' -f1 | cut -d' ' -f5-}}"
name = "uptime"
type = "label"
