name = "soironbatop"
anchor_to_edges = true
icon_theme = "breeze-dark"
position = "top"
height = 24
popup_gap = 0

# [[start]]
# all_monitors = false
# type = "workspaces"

# [start.name_map]
# 1 = "icon:firefox"

[[start]]
# favorites = [ "firefox", ]
icon_size = 18
show_icons = true
show_names = false
type = "launcher"

[[start]]
name = "sosep"
label = "|"
type = "label"

[[start]]
name = "focused-window"
type = "focused"
show_icon = true
show_title = true
icon_size = 16
truncate = "end"


[[end]]
name = "sosep"
label = "|"
type = "label"

[[end]]
class = "sovolume"
tooltip = "Volume"
type = "custom"

[[end.bar]]
name = "sovolume-btn"
on_click = "popup:toggle"
label= "{{so-volumeicon.sh}}"
type = "button"

[[end.popup]]
orientation = "v"
type = "box"

[[end.popup.widgets]]
label = "Volume Settings"
name = "header"
type = "label"

[[end.popup.widgets]]
name = "sovol-box"
type = "box"
orientation = "v"

[[end.popup.widgets.widgets]]
type = "box"
class = "vol-box"

[[end.popup.widgets.widgets.widgets]]
type = "label"
label = "Speakers:    "
class = "vol-label"

[[end.popup.widgets.widgets.widgets]]
class = "vol-slider"
label = "vol"
tooltip = "Change Volume"
type = "slider"
orientation = "h"
value = "pactl get-sink-volume @DEFAULT_SINK@ | grep \"Volume:\" | awk '{gsub(/%/, \"\", $5); print $5}'"
step = 5
#length = 150

[[end.popup.widgets.widgets.widgets]]
class = "vol-btn"
label = "OK"
on_click = ""
tooltip = "Update Volume"
type = "button"

[[end.popup.widgets.widgets]]
type = "box"
class = "vol-box"

[[end.popup.widgets.widgets.widgets]]
type = "label"
label = "Microphone:"
class = "vol-label"

[[end.popup.widgets.widgets.widgets]]
class = "vol-slider"
label = "vol"
on_click = ""
tooltip = "Change Volume"
type = "slider"
orientation = "h"
#value = ""
step = 5
#length = 150

[[end.popup.widgets.widgets.widgets]]
class = "vol-btn"
label = "OK"
on_click = ""
tooltip = "Update Volume"
type = "button"

[[end]]
name = "sosep"
label = "|"
type = "label"

[[end]]
music_dir = "/media/SDisque/Disque-S/Audio"
player_type = "mpris"
format = ""
show_status_icon =  true
icon_size = 14
type = "music"

[end.truncate]
max_length = 100
mode = "end"

[[end]]
format = [
    " {cpu_percent}% | {temp_c:coretemp-Package-id-0}°C",
    " {memory_used} GB ({memory_percent}%)",
    #"| {swap_used} / {swap_total} GB ({swap_percent}%)",
    #"| 󰋊 {disk_used:/} / {disk_total:/} GB ({disk_percent:/}%)",
    #"󰓢 {net_down:enp39s0} / {net_up:enp39s0} Mbps",
    #"󰖡 {load_average:1} | {load_average:5} | {load_average:15}",
    #"󰥔 {uptime}",
]
type = "sys_info"

[end.interval]
cpu = 1
#disks = 300
memory = 30
#networks = 3
temps = 5

[[end]]
format = "{percentage}%"
icon_size = 14
tooltip = "bat"
type = "upower"

[[end]]
max_items = 10
type = "clipboard"

# [end.truncate]
# length = 50
# mode = "end"

[[end]]
direction = "left_to_right"
type = "tray"

# [[end]]
# class = "network-btn"
# tooltip = ""
# type = "custom"
#

[[end]]
format = "%H:%M %b %d-%m"
format_popup = "%H:%M\n%d %B %Y"
type = "clock"

[[end]]
class = "power-menu"
tooltip = "Up: {{30000:uptime | cut -d',' -f1 | cut -d' ' -f5-}}"
type = "label"
label = ""
on_click_left = "wlogout -r 5 -c 5"


