# base16 minimal-5-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x0d2733'
foreground = '0xa6b2b6'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x0d2733'
cursor = '0xa6b2b6'

# Normal colors
[colors.normal]
black = '0x0d2733'
red = '0xb8511a'
green = '0x0e6b83'
yellow = '0xea9760'
blue = '0x14679f'
magenta = '0x8b4a42'
cyan = '0x47aee4'
#white = '0xa6b2b6'
white = '0xe4eaeb'

# Bright colors
[colors.bright]
black = '0x697a81'
red = '0xe57b42'
green = '0x2b424d'
yellow = '0x4a5e67'
blue = '0x87969c'
magenta = '0xc5ced0'
cyan = '0x9c3e22'
white = '0xe4eaeb'
