# base16 7-png - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x22291a'
foreground = '0x979b88'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x22291a'
cursor = '0x979b88'

# Normal colors
[colors.normal]
black = '0x22291a'
red = '0x7a7a3c'
green = '0x61733f'
yellow = '0xb2b77f'
blue = '0x4d4880'
magenta = '0x50477c'
cyan = '0x8585c3'
#white = '0x979b88'
white = '0xc7c9b5'

# Bright colors
[colors.bright]
black = '0x686d5c'
red = '0x928f58'
green = '0x393f30'
yellow = '0x515646'
blue = '0x808472'
magenta = '0xafb29e'
cyan = '0x534954'
white = '0xc7c9b5'
