# base16 extra-12-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1d282f'
foreground = '0xa09c9b'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1d282f'
cursor = '0xa09c9b'

# Normal colors
[colors.normal]
black = '0x1d282f'
red = '0xa75169'
green = '0x38976d'
yellow = '0xbbb491'
blue = '0x5a6492'
magenta = '0x977388'
cyan = '0x65b49e'
#white = '0xa09c9b'
white = '0xd5cbc7'

# Bright colors
[colors.bright]
black = '0x6b6d70'
red = '0xae917b'
green = '0x373f44'
yellow = '0x51565a'
blue = '0x868585'
magenta = '0xbab3b1'
cyan = '0x956b79'
white = '0xd5cbc7'
