#!/usr/bin/env bash

## Files and cmd
FILE="$HOME/.cache/eww_sewwbar.xyz"

if [ "$XDG_CURRENT_DESKTOP" = "Hyprland" ]; then
	EWW="eww -c $HOME/.config/eww/seww/hypr"
elif [ "$XDG_CURRENT_DESKTOP" = "labwc" ]; then
	EWW="eww -c $HOME/.config/eww/seww/lab"

	echo '["1"]' > "$HOME/.config/eww/seww/lab/workspaces.txt"
	echo '[{"title": "...", "states": [""]}]' > "$HOME/.config/eww/seww/lab/clients.txt"
elif [ "$XDG_CURRENT_DESKTOP" = "niri" ]; then
	EWW="eww -c $HOME/.config/eww/seww/niri"
else
	EWW="eww -c $HOME/.config/eww/seww/default"
fi

## Open widgets
open_eww() {
	${EWW} open sewwbar
}

start_eww() {
	touch "$FILE"

	if [ "$XDG_CURRENT_DESKTOP" = "labwc" ]; then
		lslab ~/.config/eww/scripts/lab-get-workspaces.py &
		lslab ~/.config/eww/scripts/lab-get-clients.py &
	fi

	sleep 1
	${EWW} --force-wayland daemon
}

kill_eww() {
	${EWW} close-all && ${EWW} kill

	if [ "$XDG_CURRENT_DESKTOP" = "labwc" ]; then
		pkill -f $HOME/.config/eww/scripts/lab-get-workspaces.py
		pkill -f $HOME/.config/eww/scripts/lab-get-clients.py
	fi
}

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	if [[ -f "$FILE" ]]; then
		rm "$FILE"
	fi

	start_eww
	open_eww
else
	kill_eww
fi

