# This pinnacle.toml file dictates what config Pinnacle will run.
#
# When running Pinnacle, the compositor will look in the following directories for a pinnacle.toml file,
# in order from top to bottom:
#     $PINNACLE_CONFIG_DIR
#     $XDG_CONFIG_HOME/pinnacle/
#     ~/.config/pinnacle/
#
# When Pinnacle finds a pinnacle.toml file, it will execute the command provided to `run`.
# To use a Rust config, this should be changed to something like ["cargo", "run"].

# The command Pinnacle will run on startup and when you reload your config.
# Paths are relative to the directory this file is in.
# This must be an array.
run = ["lua", "default_config.lua"]

### Socket directory ###
# Pinnacle will open a Unix socket at `$XDG_RUNTIME_DIR` by default, falling back to `/tmp` if it doesn't exist.
# If you want/need to change this, use the `socket_dir` setting set to the directory of your choosing.
#
# socket_dir = "/your/dir/here/"

### Environment Variables ###
# If you need to spawn your config with any environment variables, list them here.
[envs]
# key = "value"
GTK_THEME = "Breeze-Dark"
XDG_SESSION_DESKTOP = "Pinnacle"
XDG_CURRENT_DESKTOP = "Pinnacle"
#XDG_SESSION_TYPE = "wayland"

XCURSOR_SIZE = 24
#HYPRCURSOR_SIZE = 24
XCURSOR_THEME = "Breeze_Light"

QT_QPA_PLATFORM = "wayland"
QT_QPA_PLATFORMTHEME = "qt6ct"
QT_EXCLUDE_GENERIC_BEARER = 1
QT_AUTO_SCREEN_SCALE_FACTOR = 1 # previous value: 0
QT_ACCESSIBILITY = 1
# QT_QUICK_CONTROLS_STYLE,org.kde.desktop

QT_WAYLAND_DISABLE_WINDOWDECORATION = 1
MOZ_ENABLE_WAYLAND = 1
GDK_SCALE = 1

### No xwayland ###
# If you want to stop xwayland from starting, uncomment the field below.
# 
# no_xwayland = true

### No config ###
# If you want to stop a config from starting, uncomment the field below.
# 
# no_config = true
