#!/usr/bin/env bash

status=$(LANG=C nmcli g | grep  "disconnected")
device=$(nmcli -t c | cut -d':' -f4 | awk '{ if ($0 != "" && $0 != "lo") print $1}')
essid=$(nmcli -t c | grep $device | cut -d':' -f1)

if [ $status ] ; then
    icon=""
    text=""
    col="#575268"

else
    icon=""
    text="${essid}"
    col="#a1bdce"
fi



if [[ "$1" == "--COL" ]]; then
    echo $col	
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi

