# base16 akJj-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1e2541'
foreground = '0xb2b5bf'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1e2541'
cursor = '0xb2b5bf'

# Normal colors
[colors.normal]
black = '0x1e2541'
red = '0xea4408'
green = '0x20ad6e'
yellow = '0xf3a13c'
blue = '0x0b5dc2'
magenta = '0x725e91'
cyan = '0x3fd8b1'
#white = '0xb2b5bf'
white = '0xeeeff2'

# Bright colors
[colors.bright]
black = '0x777b8c'
red = '0xea8519'
green = '0x3b415a'
yellow = '0x595e73'
blue = '0x9498a6'
magenta = '0xd0d2d8'
cyan = '0xa0451e'
white = '0xeeeff2'
