# base16 10-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x172932'
foreground = '0x8f9ea2'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x172932'
cursor = '0x8f9ea2'

# Normal colors
[colors.normal]
black = '0x172932'
red = '0xb7404e'
green = '0x5fa869'
yellow = '0xcc9966'
blue = '0x0614c2'
magenta = '0x871675'
cyan = '0x12bde1'
#white = '0x8f9ea2'
white = '0xbfced0'

# Bright colors
[colors.bright]
black = '0x5f6f75'
red = '0xc78738'
green = '0x2f4048'
yellow = '0x47585f'
blue = '0x77878c'
magenta = '0xa7b6b9'
cyan = '0x98244d'
white = '0xbfced0'
