# base16 inkblast-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1f1d60'
foreground = '0x9e9fb9'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1f1d60'
cursor = '0x9e9fb9'

# Normal colors
[colors.normal]
black = '0x1f1d60'
red = '0xc54f38'
green = '0x33b846'
yellow = '0xeacc49'
blue = '0x454652'
magenta = '0x483e93'
cyan = '0x3ab0c7'
#white = '0x9e9fb9'
white = '0xd1d3dd'

# Bright colors
[colors.bright]
black = '0x6b6b95'
red = '0xeaa334'
green = '0x383771'
yellow = '0x515183'
blue = '0x8485a7'
magenta = '0xb7b9cb'
cyan = '0x9b3c27'
white = '0xd1d3dd'
