# base16 backgrounds-3-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x0a2228'
foreground = '0x979a93'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x0a2228'
cursor = '0x979a93'

# Normal colors
[colors.normal]
black = '0x0a2228'
red = '0x9b3037'
green = '0x038e3c'
yellow = '0xf7a345'
blue = '0x085cba'
magenta = '0x8f1863'
cyan = '0x3ccdc8'
#white = '0x979a93'
white = '0xd0cabf'

# Bright colors
[colors.bright]
black = '0x5e6a68'
red = '0xdd6a64'
green = '0x263a3d'
yellow = '0x425253'
blue = '0x7b827e'
magenta = '0xb3b2a9'
cyan = '0x603f35'
white = '0xd0cabf'
