# base16 103-result-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x2e2235'
foreground = '0xa69cab'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2e2235'
cursor = '0xa69cab'

# Normal colors
[colors.normal]
black = '0x2e2235'
red = '0x605443'
green = '0x14a64b'
yellow = '0xde8d66'
blue = '0x217299'
magenta = '0x5e486a'
cyan = '0x1af9ce'
#white = '0xa69cab'
white = '0xd7cedb'

# Bright colors
[colors.bright]
black = '0x766b7c'
red = '0xcb7350'
green = '0x463a4c'
yellow = '0x5e5364'
blue = '0x8e8493'
magenta = '0xbeb5c3'
cyan = '0x66193e'
white = '0xd7cedb'
