# base16 wallhaven-yxdvjx-png - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x222915'
foreground = '0x9fa8a4'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x222915'
cursor = '0x9fa8a4'

# Normal colors
[colors.normal]
black = '0x222915'
red = '0xc30700'
green = '0x38ad22'
yellow = '0xf9d906'
blue = '0x0a15e0'
magenta = '0x80007e'
cyan = '0x32a3cf'
#white = '0x9fa8a4'
white = '0xd2dbde'

# Bright colors
[colors.bright]
black = '0x6d756b'
red = '0xffa30f'
green = '0x3b4231'
yellow = '0x545b4e'
blue = '0x868e87'
magenta = '0xb8c1c1'
cyan = '0xa62928'
white = '0xd2dbde'
