# base16 ZkxrRA-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x342033'
foreground = '0xbab3b6'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x342033'
cursor = '0xbab3b6'

# Normal colors
[colors.normal]
black = '0x342033'
red = '0xaa5358'
green = '0x36a27a'
yellow = '0xdacf6c'
blue = '0x27329b'
magenta = '0x825280'
cyan = '0x5fb1ac'
#white = '0xbab3b6'
white = '0xf0eeeb'

# Bright colors
[colors.bright]
black = '0x847881'
red = '0xc8954d'
green = '0x4e3d4d'
yellow = '0x695a67'
blue = '0x9f959c'
magenta = '0xd5d0d0'
cyan = '0xab595c'
white = '0xf0eeeb'
