# base16 minimal-13-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x242918'
foreground = '0x999988'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x242918'
cursor = '0x999988'

# Normal colors
[colors.normal]
black = '0x242918'
red = '0x8d955a'
green = '0x8f9f52'
yellow = '0xd0ec6b'
blue = '0x2f1294'
magenta = '0x4c279a'
cyan = '0x928cb9'
#white = '0x999988'
white = '0xc9c6b5'

# Bright colors
[colors.bright]
black = '0x6a6c5b'
red = '0xb3c95b'
green = '0x3b3f2e'
yellow = '0x535544'
blue = '0x828271'
magenta = '0xb1af9e'
cyan = '0x80698e'
white = '0xc9c6b5'
