# base16 banner - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x252728'
foreground = '0xb7baba'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x252728'
cursor = '0xb7baba'

# Normal colors
[colors.normal]
black = '0x252728'
red = '0xf82304'
green = '0x50aa0e'
yellow = '0xf9a13c'
blue = '0x0021c0'
magenta = '0x8b6278'
cyan = '0x0f8ded'
#white = '0xb7baba'
white = '0xf2f6f5'

# Bright colors
[colors.bright]
black = '0x7c7f7f'
red = '0xfd8e10'
green = '0x424445'
yellow = '0x5f6262'
blue = '0x9a9d9d'
magenta = '0xd4d8d7'
cyan = '0x942809'
white = '0xf2f6f5'
