# base16 1-png - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x0d2732'
foreground = '0x939790'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x0d2732'
cursor = '0x939790'

# Normal colors
[colors.normal]
black = '0x0d2732'
red = '0xe5173e'
green = '0x1ebc89'
yellow = '0xedb47d'
blue = '0x1738c3'
magenta = '0x862c60'
cyan = '0x14ecd4'
#white = '0x939790'
white = '0xc9c4b6'

# Bright colors
[colors.bright]
black = '0x5d6a6a'
red = '0xd99070'
green = '0x273d44'
yellow = '0x425357'
blue = '0x78807d'
magenta = '0xaeada3'
cyan = '0xb62440'
white = '0xc9c4b6'
