# base16 9-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x272726'
foreground = '0xa6adab'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x272726'
cursor = '0xa6adab'

# Normal colors
[colors.normal]
black = '0x272726'
red = '0x9e342d'
green = '0x407655'
yellow = '0xeaa969'
blue = '0x155696'
magenta = '0x5f276d'
cyan = '0x61cbd2'
#white = '0xa6adab'
white = '0xdae3e1'

# Bright colors
[colors.bright]
black = '0x737776'
red = '0xe1875a'
green = '0x404140'
yellow = '0x5a5c5b'
blue = '0x8d9290'
magenta = '0xc0c8c6'
cyan = '0x937059'
white = '0xdae3e1'
