# base16 fly-jpeg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x222829'
foreground = '0xb1b4b5'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x222829'
cursor = '0xb1b4b5'

# Normal colors
[colors.normal]
black = '0x222829'
red = '0x8b7a74'
green = '0x748e82'
yellow = '0xb1a18f'
blue = '0x667c93'
magenta = '0x89787d'
cyan = '0x9eaaae'
#white = '0xb1b4b5'
white = '0xebeced'

# Bright colors
[colors.bright]
black = '0x787c7d'
red = '0xa69889'
green = '0x3e4445'
yellow = '0x5b6061'
blue = '0x949899'
magenta = '0xced0d1'
cyan = '0x8b7a74'
white = '0xebeced'
