# base16 snow-png - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x0f3c3c'
foreground = '0x97acad'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x0f3c3c'
cursor = '0x97acad'

# Normal colors
[colors.normal]
black = '0x0f3c3c'
red = '0xaf4c1d'
green = '0x25a36e'
yellow = '0x9a5f2d'
blue = '0x65a0d2'
magenta = '0xc94c88'
cyan = '0x50b3e2'
#white = '0x97acad'
white = '0xcedadb'

# Bright colors
[colors.bright]
black = '0x607f80'
red = '0xae4e1e'
green = '0x2a5252'
yellow = '0x456969'
blue = '0x7c9696'
magenta = '0xb2c3c4'
cyan = '0xa0451b'
white = '0xcedadb'
