# base16 pos2-png - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x252729'
foreground = '0x939f9f'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x252729'
cursor = '0x939f9f'

# Normal colors
[colors.normal]
black = '0x252729'
red = '0xb23d41'
green = '0x098379'
yellow = '0xf59893'
blue = '0x0a676c'
magenta = '0x8b404a'
cyan = '0x4dc2be'
#white = '0x939f9f'
white = '0xc0cfcf'

# Bright colors
[colors.bright]
black = '0x676f70'
red = '0xd76e67'
green = '0x3b3f40'
yellow = '0x515758'
blue = '0x7d8787'
magenta = '0xa9b7b7'
cyan = '0x855b5b'
white = '0xc0cfcf'
