# base16 2-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x202542'
foreground = '0xa69fab'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x202542'
cursor = '0xa69fab'

# Normal colors
[colors.normal]
black = '0x202542'
red = '0xc4595a'
green = '0x0f764a'
yellow = '0xd1b950'
blue = '0x2e46af'
magenta = '0x524a63'
cyan = '0x3ba6a5'
#white = '0xa69fab'
white = '0xdcd0d6'

# Bright colors
[colors.bright]
black = '0x706e81'
red = '0xc6a93c'
green = '0x3a3d57'
yellow = '0x55556c'
blue = '0x8b8696'
magenta = '0xc1b7c0'
cyan = '0x9d5455'
white = '0xdcd0d6'
