# base16 minimal-14-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x2f251f'
foreground = '0xa09da5'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2f251f'
cursor = '0xa09da5'

# Normal colors
[colors.normal]
black = '0x2f251f'
red = '0xaa7551'
green = '0x76956d'
yellow = '0xffc46f'
blue = '0x003b90'
magenta = '0x566595'
cyan = '0x5e90b2'
#white = '0xa09da5'
white = '0xcecedb'

# Bright colors
[colors.bright]
black = '0x736d6f'
red = '0xf2ad64'
green = '0x453d39'
yellow = '0x5c5554'
blue = '0x89858a'
magenta = '0xb7b5c0'
cyan = '0x9c7f71'
white = '0xcecedb'
