# base16 adaptive-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1d292c'
foreground = '0x8d9a9e'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1d292c'
cursor = '0x8d9a9e'

# Normal colors
[colors.normal]
black = '0x1d292c'
red = '0xc3767d'
green = '0x006756'
yellow = '0xd5988d'
blue = '0x2a6772'
magenta = '0xc3767d'
cyan = '0x3c8982'
#white = '0x8d9a9e'
white = '0xbac8cc'

# Bright colors
[colors.bright]
black = '0x606d70'
red = '0xd58283'
green = '0x333f42'
yellow = '0x495659'
blue = '0x768387'
magenta = '0xa3b1b5'
cyan = '0x422f43'
white = '0xbac8cc'
