# base16 colors-png - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x441a11'
foreground = '0xb09c9d'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x441a11'
cursor = '0xb09c9d'

# Normal colors
[colors.normal]
black = '0x441a11'
red = '0xed4a51'
green = '0x238474'
yellow = '0xa06a3f'
blue = '0x0539b7'
magenta = '0x653375'
cyan = '0x12b5ae'
#white = '0xb09c9d'
white = '0xdcd0d6'

# Bright colors
[colors.bright]
black = '0x856865'
red = '0xa1683e'
green = '0x59342d'
yellow = '0x6f4e49'
blue = '0x9a8281'
magenta = '0xc6b6b9'
cyan = '0x9c412e'
white = '0xdcd0d6'
