# base16 00012-250_k_lms_1468565384_0-00-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x312132'
foreground = '0x899494'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x312132'
cursor = '0x899494'

# Normal colors
[colors.normal]
black = '0x312132'
red = '0xe62129'
green = '0x00a472'
yellow = '0xe99d73'
blue = '0x0035ff'
magenta = '0x695669'
cyan = '0x04d9d7'
#white = '0x899494'
white = '0xadc3bc'

# Bright colors
[colors.bright]
black = '0x66666d'
red = '0xfa6538'
green = '0x423845'
yellow = '0x544f59'
blue = '0x777d80'
magenta = '0x9baba8'
cyan = '0xcd384f'
white = '0xadc3bc'
