# base16 minimal-15-png - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x331c46'
foreground = '0xada3af'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x331c46'
cursor = '0xada3af'

# Normal colors
[colors.normal]
black = '0x331c46'
red = '0x7d631d'
green = '0x5c9441'
yellow = '0xf0b17e'
blue = '0x0f5185'
magenta = '0x6c3791'
cyan = '0xa6b8ea'
#white = '0xada3af'
white = '0xdfdada'

# Bright colors
[colors.bright]
black = '0x7c6d85'
red = '0xf0b17e'
green = '0x4b375b'
yellow = '0x645270'
blue = '0x95889a'
magenta = '0xc6bec4'
cyan = '0x7e6520'
white = '0xdfdada'
