# base16 nature-15-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x35221b'
foreground = '0xa0978c'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x35221b'
cursor = '0xa0978c'

# Normal colors
[colors.normal]
black = '0x35221b'
red = '0x687d96'
green = '0x239e95'
yellow = '0xe1d168'
blue = '0x1e2e99'
magenta = '0x4a489b'
cyan = '0x18e9e5'
#white = '0xa0978c'
white = '0xccc7ba'

# Bright colors
[colors.bright]
black = '0x75685f'
red = '0x91a3a5'
green = '0x4a3931'
yellow = '0x605148'
blue = '0x8b8075'
magenta = '0xb6afa3'
cyan = '0xa12928'
white = '0xccc7ba'
