# base16 arc-png - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1a273a'
foreground = '0x969abd'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1a273a'
cursor = '0x969abd'

# Normal colors
[colors.normal]
black = '0x1a273a'
red = '0xad6b1d'
green = '0x3f4551'
yellow = '0xb98b52'
blue = '0x4674ad'
magenta = '0x4c3c60'
cyan = '0x5294e2'
#white = '0x969abd'
white = '0xc8c8f2'

# Bright colors
[colors.bright]
black = '0x646c88'
red = '0xb1742c'
green = '0x323e54'
yellow = '0x4b556e'
blue = '0x7d83a3'
magenta = '0xafb1d7'
cyan = '0xad6b1d'
white = '0xc8c8f2'
