# base16 bird-png - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x2c261e'
foreground = '0xbcbab6'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2c261e'
cursor = '0xbcbab6'

# Normal colors
[colors.normal]
black = '0x2c261e'
red = '0xa04d20'
green = '0x325266'
yellow = '0xe1c355'
blue = '0x1e3caa'
magenta = '0x764d36'
cyan = '0x5fb2df'
#white = '0xbcbab6'
white = '0xf6f6f4'

# Bright colors
[colors.bright]
black = '0x827f79'
red = '0x62809a'
green = '0x48433c'
yellow = '0x65615b'
blue = '0x9f9c98'
magenta = '0xd9d8d5'
cyan = '0x975c34'
white = '0xf6f6f4'
