# base16 horizon_by_aenami_dd7ziro-png - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1f243d'
foreground = '0xa7a9a8'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1f243d'
cursor = '0xa7a9a8'

# Normal colors
[colors.normal]
black = '0x1f243d'
red = '0xb1433c'
green = '0x179d8b'
yellow = '0xd4b65b'
blue = '0x101dc5'
magenta = '0x544d66'
cyan = '0x4ebcc3'
#white = '0xa7a9a8'
white = '0xdedfd4'

# Bright colors
[colors.bright]
black = '0x70747d'
red = '0xcea355'
green = '0x3a3e52'
yellow = '0x555968'
blue = '0x8c8e93'
magenta = '0xc2c4be'
cyan = '0xb64c4d'
white = '0xdedfd4'
