# base16 minimal-7-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x0d2833'
foreground = '0xb5bec0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x0d2833'
cursor = '0xb5bec0'

# Normal colors
[colors.normal]
black = '0x0d2833'
red = '0x9a5626'
green = '0x847632'
yellow = '0xcfa77a'
blue = '0x376599'
magenta = '0x896966'
cyan = '0x6daddb'
#white = '0xb5bec0'
white = '0xf9fbf9'

# Bright colors
[colors.bright]
black = '0x728287'
red = '0xb17f4c'
green = '0x2e464f'
yellow = '0x50646b'
blue = '0x93a0a4'
magenta = '0xd7dcdc'
cyan = '0x965323'
white = '0xf9fbf9'
