# base16 3-png - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1d234d'
foreground = '0xa7a0ae'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1d234d'
cursor = '0xa7a0ae'

# Normal colors
[colors.normal]
black = '0x1d234d'
red = '0xc31f26'
green = '0x22aa66'
yellow = '0xf1bc4c'
blue = '0x0e43b3'
magenta = '0x682f58'
cyan = '0x5abfc2'
#white = '0xa7a0ae'
white = '0xdfd3d5'

# Bright colors
[colors.bright]
black = '0x706e87'
red = '0xe69231'
green = '0x383c60'
yellow = '0x545573'
blue = '0x8b879a'
magenta = '0xc3b9c1'
cyan = '0xa05249'
white = '0xdfd3d5'
