# base16 grass-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x2b2524'
foreground = '0xa6a09a'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2b2524'
cursor = '0xa6a09a'

# Normal colors
[colors.normal]
black = '0x2b2524'
red = '0xc95527'
green = '0x3fae75'
yellow = '0xf7b74c'
blue = '0x083ed4'
magenta = '0x895194'
cyan = '0x36aad7'
#white = '0xa6a09a'
white = '0xd8d2ca'

# Bright colors
[colors.bright]
black = '0x756f6b'
red = '0xf67c25'
green = '0x433d3b'
yellow = '0x5c5653'
blue = '0x8d8782'
magenta = '0xbfb9b2'
cyan = '0xa95c6a'
white = '0xd8d2ca'
