# base16 nature-7-jpg - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x34231d'
foreground = '0xb7b2ab'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x34231d'
cursor = '0xb7b2ab'

# Normal colors
[colors.normal]
black = '0x34231d'
red = '0x986a5c'
green = '0x5de34c'
yellow = '0xaddc57'
blue = '0x1e36da'
magenta = '0x842c8e'
cyan = '0x22c3c3'
#white = '0xb7b2ab'
white = '0xecece5'

# Bright colors
[colors.bright]
black = '0x827972'
red = '0x9dac4b'
green = '0x4e3f39'
yellow = '0x685c56'
blue = '0x9d958f'
magenta = '0xd1cfc8'
cyan = '0x94735f'
white = '0xecece5'
