# base24 coran - alacritty color config
# Tinty

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x21234a'
foreground = '0xb5b5bd'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x21234a'
cursor = '0xb5b5bd'

# Normal colors
[colors.normal]
black = '0x21234a'
red = '0xb5370c'
green = '0x358e4f'
yellow = '0xd7d15e'
blue = '0x002bd0'
magenta = '0x454891'
cyan = '0x21e8e3'
#white = '0xb5b5bd'
white = '0xf1f0ec'
#
# Bright colors
[colors.bright]
black = '0x7a7a8f'
red = '0xb8b57c'
green = '0x53b5b2'
yellow = '0x4b7758'
blue = '0x58597d'
magenta = '0x944d4c'
cyan = '0x354a9a'
white = '0xf1f0ec'

