
[[manager.prepend_keymap]]
on   = [ "c", "m" ]
run = "plugin mount"

[[manager.prepend_keymap]]
on   = "C-X"
run  = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on   = "C-T"
run  = "plugin hide-preview"
desc = "Hide or show preview"

[[manager.prepend_keymap]]
on   = "Enter"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
]

[[manager.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[manager.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[manager.prepend_keymap]]
on = "<C-y>"
run = ["plugin wl-clipboard"]
