# base16 minimal-10-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x3a2018'
foreground = '0xa8a195'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x3a2018'
cursor = '0xa8a195'

# Normal colors
[colors.normal]
black = '0x3a2018'
red = '0x9a474c'
green = '0x0c7768'
yellow = '0xd3a08c'
blue = '0x0341cb'
magenta = '0x8d406e'
cyan = '0x27bfd8'
#white = '0xa8a195'
white = '0xd5d5c7'

# Bright colors
[colors.bright]
black = '0x7c6d63'
red = '0x9a474c'
green = '0x0c7768'
yellow = '0xd3a08c'
blue = '0x0341cb'
magenta = '0x8d406e'
cyan = '0x27bfd8'
white = '0xd5d5c7'

[[colors.indexed_colors]]
index = 16
color = "0xfbab38"

[[colors.indexed_colors]]
index = 17
color = "0xc75834"

[[colors.indexed_colors]]
index = 18
color = "0x503931"

[[colors.indexed_colors]]
index = 19
color = "0x66534a"

[[colors.indexed_colors]]
index = 20
color = "0x92877c"

[[colors.indexed_colors]]
index = 21
color = "0xbebbae"
