# base16 wallpaperflare-com_wallpaper4-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x252537'
foreground = '0xaca7ac'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x252537'
cursor = '0xaca7ac'

# Normal colors
[colors.normal]
black = '0x252537'
red = '0xa26119'
green = '0x4a7259'
yellow = '0xccbb4a'
blue = '0x3344b5'
magenta = '0x4b4c6c'
cyan = '0x5d9ee6'
#white = '0xaca7ac'
white = '0xe2dbdb'

# Bright colors
[colors.bright]
black = '0x76737d'
red = '0xa26119'
green = '0x4a7259'
yellow = '0xccbb4a'
blue = '0x3344b5'
magenta = '0x4b4c6c'
cyan = '0x5d9ee6'
white = '0xe2dbdb'

[[colors.indexed_colors]]
index = 16
color = "0xcd8f67"

[[colors.indexed_colors]]
index = 17
color = "0x846b45"

[[colors.indexed_colors]]
index = 18
color = "0x403f4e"

[[colors.indexed_colors]]
index = 19
color = "0x5b5965"

[[colors.indexed_colors]]
index = 20
color = "0x918d94"

[[colors.indexed_colors]]
index = 21
color = "0xc7c1c3"
