# base16 6-png 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x1e2833'
foreground = '0xacb3b1'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1e2833'
cursor = '0xacb3b1'

# Normal colors
[colors.normal]
black = '0x1e2833'
red = '0xce482d'
green = '0x4e973e'
yellow = '0xffd04e'
blue = '0x080ff5'
magenta = '0x632b72'
cyan = '0x37c2eb'
#white = '0xacb3b1'
white = '0xe6ebe4'

# Bright colors
[colors.bright]
black = '0x737b7e'
red = '0xce482d'
green = '0x4e973e'
yellow = '0xffd04e'
blue = '0x080ff5'
magenta = '0x632b72'
cyan = '0x37c2eb'
white = '0xe6ebe4'

[[colors.indexed_colors]]
index = 16
color = "0xf1a42e"

[[colors.indexed_colors]]
index = 17
color = "0xa76c34"

[[colors.indexed_colors]]
index = 18
color = "0x3a434c"

[[colors.indexed_colors]]
index = 19
color = "0x575f65"

[[colors.indexed_colors]]
index = 20
color = "0x909798"

[[colors.indexed_colors]]
index = 21
color = "0xc9cfca"
