# base16 yosemite-png 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x132648'
foreground = '0xabaaba'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x132648'
cursor = '0xabaaba'

# Normal colors
[colors.normal]
black = '0x132648'
red = '0xb37938'
green = '0x379759'
yellow = '0xe7ab5e'
blue = '0x1753a1'
magenta = '0x868967'
cyan = '0x4c86c7'
#white = '0xabaaba'
white = '0xe8e0e8'

# Bright colors
[colors.bright]
black = '0x6e758c'
red = '0xb37938'
green = '0x379759'
yellow = '0xe7ab5e'
blue = '0x1753a1'
magenta = '0x868967'
cyan = '0x4c86c7'
white = '0xe8e0e8'

[[colors.indexed_colors]]
index = 16
color = "0xe18e4c"

[[colors.indexed_colors]]
index = 17
color = "0x9c7432"

[[colors.indexed_colors]]
index = 18
color = "0x31405e"

[[colors.indexed_colors]]
index = 19
color = "0x4f5b75"

[[colors.indexed_colors]]
index = 20
color = "0x8c90a3"

[[colors.indexed_colors]]
index = 21
color = "0xc9c5d1"
