# base16 banner 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x252728'
foreground = '0xb7baba'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x252728'
cursor = '0xb7baba'

# Normal colors
[colors.normal]
black = '0x252728'
red = '0xf82304'
green = '0x50aa0e'
yellow = '0xf9a13c'
blue = '0x0021c0'
magenta = '0x8b6278'
cyan = '0x0f8ded'
#white = '0xb7baba'
white = '0xf2f6f5'

# Bright colors
[colors.bright]
black = '0x7c7f7f'
red = '0xf82304'
green = '0x50aa0e'
yellow = '0xf9a13c'
blue = '0x0021c0'
magenta = '0x8b6278'
cyan = '0x0f8ded'
white = '0xf2f6f5'

[[colors.indexed_colors]]
index = 16
color = "0xfd8e10"

[[colors.indexed_colors]]
index = 17
color = "0x942809"

[[colors.indexed_colors]]
index = 18
color = "0x424445"

[[colors.indexed_colors]]
index = 19
color = "0x5f6262"

[[colors.indexed_colors]]
index = 20
color = "0x9a9d9d"

[[colors.indexed_colors]]
index = 21
color = "0xd4d8d7"
