# base16 colors-png 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x441a11'
foreground = '0xb09c9d'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x441a11'
cursor = '0xb09c9d'

# Normal colors
[colors.normal]
black = '0x441a11'
red = '0xed4a51'
green = '0x238474'
yellow = '0xa06a3f'
blue = '0x0539b7'
magenta = '0x653375'
cyan = '0x12b5ae'
#white = '0xb09c9d'
white = '0xdcd0d6'

# Bright colors
[colors.bright]
black = '0x856865'
red = '0xed4a51'
green = '0x238474'
yellow = '0xa06a3f'
blue = '0x0539b7'
magenta = '0x653375'
cyan = '0x12b5ae'
white = '0xdcd0d6'

[[colors.indexed_colors]]
index = 16
color = "0xa1683e"

[[colors.indexed_colors]]
index = 17
color = "0x9c412e"

[[colors.indexed_colors]]
index = 18
color = "0x59342d"

[[colors.indexed_colors]]
index = 19
color = "0x6f4e49"

[[colors.indexed_colors]]
index = 20
color = "0x9a8281"

[[colors.indexed_colors]]
index = 21
color = "0xc6b6b9"
