# base16 photo-1508166159374-08190ea39268-jpeg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x21282a'
foreground = '0xa3a59c'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x21282a'
cursor = '0xa3a59c'

# Normal colors
[colors.normal]
black = '0x21282a'
red = '0x9b4751'
green = '0x5b8e84'
yellow = '0xcc9d79'
blue = '0x3a719a'
magenta = '0x89728c'
cyan = '0x7cc3ba'
#white = '0xa3a59c'
white = '0xd8d8ca'

# Bright colors
[colors.bright]
black = '0x6f736e'
red = '0x9b4751'
green = '0x5b8e84'
yellow = '0xcc9d79'
blue = '0x3a719a'
magenta = '0x89728c'
cyan = '0x7cc3ba'
white = '0xd8d8ca'

[[colors.indexed_colors]]
index = 16
color = "0xc6906c"

[[colors.indexed_colors]]
index = 17
color = "0x8a8a78"

[[colors.indexed_colors]]
index = 18
color = "0x3b4140"

[[colors.indexed_colors]]
index = 19
color = "0x555a57"

[[colors.indexed_colors]]
index = 20
color = "0x898c85"

[[colors.indexed_colors]]
index = 21
color = "0xbdbeb3"
