# base16 minimal-14-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x2f251f'
foreground = '0xa09da5'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2f251f'
cursor = '0xa09da5'

# Normal colors
[colors.normal]
black = '0x2f251f'
red = '0xaa7551'
green = '0x76956d'
yellow = '0xffc46f'
blue = '0x003b90'
magenta = '0x566595'
cyan = '0x5e90b2'
#white = '0xa09da5'
white = '0xcecedb'

# Bright colors
[colors.bright]
black = '0x736d6f'
red = '0xaa7551'
green = '0x76956d'
yellow = '0xffc46f'
blue = '0x003b90'
magenta = '0x566595'
cyan = '0x5e90b2'
white = '0xcecedb'

[[colors.indexed_colors]]
index = 16
color = "0xf2ad64"

[[colors.indexed_colors]]
index = 17
color = "0x9c7f71"

[[colors.indexed_colors]]
index = 18
color = "0x453d39"

[[colors.indexed_colors]]
index = 19
color = "0x5c5554"

[[colors.indexed_colors]]
index = 20
color = "0x89858a"

[[colors.indexed_colors]]
index = 21
color = "0xb7b5c0"
