# base16 wallhaven-3lp2md-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x29201b'
foreground = '0xa29c93'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x29201b'
cursor = '0xa29c93'

# Normal colors
[colors.normal]
black = '0x29201b'
red = '0xc33400'
green = '0x62b001'
yellow = '0xeea25b'
blue = '0x0000ff'
magenta = '0x61138c'
cyan = '0x16dffd'
#white = '0xa29c93'
white = '0xd3cec4'

# Bright colors
[colors.bright]
black = '0x716a63'
red = '0xc33400'
green = '0x62b001'
yellow = '0xeea25b'
blue = '0x0000ff'
magenta = '0x61138c'
cyan = '0x16dffd'
white = '0xd3cec4'

[[colors.indexed_colors]]
index = 16
color = "0xce8d31"

[[colors.indexed_colors]]
index = 17
color = "0xc24e15"

[[colors.indexed_colors]]
index = 18
color = "0x413833"

[[colors.indexed_colors]]
index = 19
color = "0x59514b"

[[colors.indexed_colors]]
index = 20
color = "0x8a837b"

[[colors.indexed_colors]]
index = 21
color = "0xbab5ab"
