# base24 Tinty Generated 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x0d2732'
foreground = '0x939790'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x0d2732'
cursor = '0x939790'

# Normal colors
[colors.normal]
black = '0x0d2732'
red = '0xe5173e'
green = '0x1ebc89'
yellow = '0xedb47d'
blue = '0x1738c3'
magenta = '0x862c60'
cyan = '0x14ecd4'
#white = '0x939790'
white = '0xc9c4b6'

# Bright colors
[colors.bright]
black = '0x5d6a6a'
red = '0xd0b499'
green = '0x4bb4a9'
yellow = '0x46937a'
blue = '0x6f425c'
magenta = '0x904956'
cyan = '0x425397'
white = '0xc9c4b6'

[[colors.indexed_colors]]
index = 16
color = "0xd99070"

[[colors.indexed_colors]]
index = 17
color = "0xb62440"

[[colors.indexed_colors]]
index = 18
color = "0x273d44"

[[colors.indexed_colors]]
index = 19
color = "0x425357"

[[colors.indexed_colors]]
index = 20
color = "0x78807d"

[[colors.indexed_colors]]
index = 21
color = "0xaeada3"
