# base16 pos2-png 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x252729'
foreground = '0x939f9f'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x252729'
cursor = '0x939f9f'

# Normal colors
[colors.normal]
black = '0x252729'
red = '0xb23d41'
green = '0x098379'
yellow = '0xf59893'
blue = '0x0a676c'
magenta = '0x8b404a'
cyan = '0x4dc2be'
#white = '0x939f9f'
white = '0xc0cfcf'

# Bright colors
[colors.bright]
black = '0x676f70'
red = '0xb23d41'
green = '0x098379'
yellow = '0xf59893'
blue = '0x0a676c'
magenta = '0x8b404a'
cyan = '0x4dc2be'
white = '0xc0cfcf'

[[colors.indexed_colors]]
index = 16
color = "0xd76e67"

[[colors.indexed_colors]]
index = 17
color = "0x855b5b"

[[colors.indexed_colors]]
index = 18
color = "0x3b3f40"

[[colors.indexed_colors]]
index = 19
color = "0x515758"

[[colors.indexed_colors]]
index = 20
color = "0x7d8787"

[[colors.indexed_colors]]
index = 21
color = "0xa9b7b7"
