# base16 snow-png 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x0f3c3c'
foreground = '0x97acad'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x0f3c3c'
cursor = '0x97acad'

# Normal colors
[colors.normal]
black = '0x0f3c3c'
red = '0xaf4c1d'
green = '0x25a36e'
yellow = '0x9a5f2d'
blue = '0x65a0d2'
magenta = '0xc94c88'
cyan = '0x50b3e2'
#white = '0x97acad'
white = '0xcedadb'

# Bright colors
[colors.bright]
black = '0x607f80'
red = '0xaf4c1d'
green = '0x25a36e'
yellow = '0x9a5f2d'
blue = '0x65a0d2'
magenta = '0xc94c88'
cyan = '0x50b3e2'
white = '0xcedadb'

[[colors.indexed_colors]]
index = 16
color = "0xae4e1e"

[[colors.indexed_colors]]
index = 17
color = "0xa0451b"

[[colors.indexed_colors]]
index = 18
color = "0x2a5252"

[[colors.indexed_colors]]
index = 19
color = "0x456969"

[[colors.indexed_colors]]
index = 20
color = "0x7c9696"

[[colors.indexed_colors]]
index = 21
color = "0xb2c3c4"
