# base16 pastel-png 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x152646'
foreground = '0xabaab6'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x152646'
cursor = '0xabaab6'

# Normal colors
[colors.normal]
black = '0x152646'
red = '0xb57d3c'
green = '0x389559'
yellow = '0xeeb167'
blue = '0x104e98'
magenta = '0x877e3f'
cyan = '0x4a81c3'
#white = '0xabaab6'
white = '0xe8dfe4'

# Bright colors
[colors.bright]
black = '0x6f7589'
red = '0xb57d3c'
green = '0x389559'
yellow = '0xeeb167'
blue = '0x104e98'
magenta = '0x877e3f'
cyan = '0x4a81c3'
white = '0xe8dfe4'

[[colors.indexed_colors]]
index = 16
color = "0xdc994f"

[[colors.indexed_colors]]
index = 17
color = "0x997c3c"

[[colors.indexed_colors]]
index = 18
color = "0x33405c"

[[colors.indexed_colors]]
index = 19
color = "0x515a73"

[[colors.indexed_colors]]
index = 20
color = "0x8d8fa0"

[[colors.indexed_colors]]
index = 21
color = "0xc9c4cd"
