# base16 extra-12-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x1d282f'
foreground = '0xa09c9b'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1d282f'
cursor = '0xa09c9b'

# Normal colors
[colors.normal]
black = '0x1d282f'
red = '0xa75169'
green = '0x38976d'
yellow = '0xbbb491'
blue = '0x5a6492'
magenta = '0x977388'
cyan = '0x65b49e'
#white = '0xa09c9b'
white = '0xd5cbc7'

# Bright colors
[colors.bright]
black = '0x6b6d70'
red = '0xa75169'
green = '0x38976d'
yellow = '0xbbb491'
blue = '0x5a6492'
magenta = '0x977388'
cyan = '0x65b49e'
white = '0xd5cbc7'

[[colors.indexed_colors]]
index = 16
color = "0xae917b"

[[colors.indexed_colors]]
index = 17
color = "0x956b79"

[[colors.indexed_colors]]
index = 18
color = "0x373f44"

[[colors.indexed_colors]]
index = 19
color = "0x51565a"

[[colors.indexed_colors]]
index = 20
color = "0x868585"

[[colors.indexed_colors]]
index = 21
color = "0xbab3b1"
