# base16 coran 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x21234a'
foreground = '0xb5b5bd'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x21234a'
cursor = '0xb5b5bd'

# Normal colors
[colors.normal]
black = '0x21234a'
red = '0xb5370c'
green = '0x358e4f'
yellow = '0xd7d15e'
blue = '0x002bd0'
magenta = '0x454891'
cyan = '0x21e8e3'
#white = '0xb5b5bd'
white = '0xf1f0ec'

# Bright colors
[colors.bright]
black = '0x7a7a8f'
red = '0xb5370c'
green = '0x358e4f'
yellow = '0xd7d15e'
blue = '0x002bd0'
magenta = '0x454891'
cyan = '0x21e8e3'
white = '0xf1f0ec'

[[colors.indexed_colors]]
index = 16
color = "0xfac82f"

[[colors.indexed_colors]]
index = 17
color = "0xb92928"

[[colors.indexed_colors]]
index = 18
color = "0x3e4061"

[[colors.indexed_colors]]
index = 19
color = "0x5c5d78"

[[colors.indexed_colors]]
index = 20
color = "0x9798a6"

[[colors.indexed_colors]]
index = 21
color = "0xd3d2d4"
