# base16 2-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x202542'
foreground = '0xa69fab'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x202542'
cursor = '0xa69fab'

# Normal colors
[colors.normal]
black = '0x202542'
red = '0xc4595a'
green = '0x0f764a'
yellow = '0xd1b950'
blue = '0x2e46af'
magenta = '0x524a63'
cyan = '0x3ba6a5'
#white = '0xa69fab'
white = '0xdcd0d6'

# Bright colors
[colors.bright]
black = '0x706e81'
red = '0xc4595a'
green = '0x0f764a'
yellow = '0xd1b950'
blue = '0x2e46af'
magenta = '0x524a63'
cyan = '0x3ba6a5'
white = '0xdcd0d6'

[[colors.indexed_colors]]
index = 16
color = "0xc6a93c"

[[colors.indexed_colors]]
index = 17
color = "0x9d5455"

[[colors.indexed_colors]]
index = 18
color = "0x3a3d57"

[[colors.indexed_colors]]
index = 19
color = "0x55556c"

[[colors.indexed_colors]]
index = 20
color = "0x8b8696"

[[colors.indexed_colors]]
index = 21
color = "0xc1b7c0"
