# base16 minimal-13-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x242918'
foreground = '0x999988'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x242918'
cursor = '0x999988'

# Normal colors
[colors.normal]
black = '0x242918'
red = '0x8d955a'
green = '0x8f9f52'
yellow = '0xd0ec6b'
blue = '0x2f1294'
magenta = '0x4c279a'
cyan = '0x928cb9'
#white = '0x999988'
white = '0xc9c6b5'

# Bright colors
[colors.bright]
black = '0x6a6c5b'
red = '0x8d955a'
green = '0x8f9f52'
yellow = '0xd0ec6b'
blue = '0x2f1294'
magenta = '0x4c279a'
cyan = '0x928cb9'
white = '0xc9c6b5'

[[colors.indexed_colors]]
index = 16
color = "0xb3c95b"

[[colors.indexed_colors]]
index = 17
color = "0x80698e"

[[colors.indexed_colors]]
index = 18
color = "0x3b3f2e"

[[colors.indexed_colors]]
index = 19
color = "0x535544"

[[colors.indexed_colors]]
index = 20
color = "0x828271"

[[colors.indexed_colors]]
index = 21
color = "0xb1af9e"
