# base16 extra-11-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x1b292d'
foreground = '0xa7b0ac'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1b292d'
cursor = '0xa7b0ac'

# Normal colors
[colors.normal]
black = '0x1b292d'
red = '0x9f6362'
green = '0x7b8c7e'
yellow = '0xbdb599'
blue = '0x5c678e'
magenta = '0x935961'
cyan = '0x77abac'
#white = '0xa7b0ac'
white = '0xdfe7e0'

# Bright colors
[colors.bright]
black = '0x6f7a79'
red = '0x9f6362'
green = '0x7b8c7e'
yellow = '0xbdb599'
blue = '0x5c678e'
magenta = '0x935961'
cyan = '0x77abac'
white = '0xdfe7e0'

[[colors.indexed_colors]]
index = 16
color = "0xa58b79"

[[colors.indexed_colors]]
index = 17
color = "0x847784"

[[colors.indexed_colors]]
index = 18
color = "0x374446"

[[colors.indexed_colors]]
index = 19
color = "0x535f60"

[[colors.indexed_colors]]
index = 20
color = "0x8b9593"

[[colors.indexed_colors]]
index = 21
color = "0xc3cbc6"
