# base16 wave-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x182835'
foreground = '0xa39a92'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x182835'
cursor = '0xa39a92'

# Normal colors
[colors.normal]
black = '0x182835'
red = '0xab6238'
green = '0x2c7e68'
yellow = '0xb08b4d'
blue = '0x4f74b2'
magenta = '0x764955'
cyan = '0x549dc7'
#white = '0xa39a92'
white = '0xdbc8b8'

# Bright colors
[colors.bright]
black = '0x6b6c6d'
red = '0xab6238'
green = '0x2c7e68'
yellow = '0xb08b4d'
blue = '0x4f74b2'
magenta = '0x764955'
cyan = '0x549dc7'
white = '0xdbc8b8'

[[colors.indexed_colors]]
index = 16
color = "0xb87f4c"

[[colors.indexed_colors]]
index = 17
color = "0x8d5452"

[[colors.indexed_colors]]
index = 18
color = "0x333e47"

[[colors.indexed_colors]]
index = 19
color = "0x4f555a"

[[colors.indexed_colors]]
index = 20
color = "0x87837f"

[[colors.indexed_colors]]
index = 21
color = "0xbfb1a5"
