# base16 akFlQGFb-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x28262e'
foreground = '0xa39b9a'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x28262e'
cursor = '0xa39b9a'

# Normal colors
[colors.normal]
black = '0x28262e'
red = '0xdb285b'
green = '0x07c374'
yellow = '0xdfa673'
blue = '0x225f96'
magenta = '0x777086'
cyan = '0x23d6a3'
#white = '0xa39b9a'
white = '0xd5cbc6'

# Bright colors
[colors.bright]
black = '0x726c6f'
red = '0xdb285b'
green = '0x07c374'
yellow = '0xdfa673'
blue = '0x225f96'
magenta = '0x777086'
cyan = '0x23d6a3'
white = '0xd5cbc6'

[[colors.indexed_colors]]
index = 16
color = "0xe3735e"

[[colors.indexed_colors]]
index = 17
color = "0xb13654"

[[colors.indexed_colors]]
index = 18
color = "0x403d43"

[[colors.indexed_colors]]
index = 19
color = "0x595559"

[[colors.indexed_colors]]
index = 20
color = "0x8a8484"

[[colors.indexed_colors]]
index = 21
color = "0xbcb3b0"
