# base16 grass-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x2b2524'
foreground = '0xa6a09a'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2b2524'
cursor = '0xa6a09a'

# Normal colors
[colors.normal]
black = '0x2b2524'
red = '0xc95528'
green = '0x3fae75'
yellow = '0xf7b74d'
blue = '0x093ed4'
magenta = '0x6a3f72'
cyan = '0x36aad7'
#white = '0xa6a09a'
white = '0xd8d2ca'

# Bright colors
[colors.bright]
black = '0x756f6b'
red = '0xc95528'
green = '0x3fae75'
yellow = '0xf7b74d'
blue = '0x093ed4'
magenta = '0x6a3f72'
cyan = '0x36aad7'
white = '0xd8d2ca'

[[colors.indexed_colors]]
index = 16
color = "0xf67c26"

[[colors.indexed_colors]]
index = 17
color = "0xa25563"

[[colors.indexed_colors]]
index = 18
color = "0x433d3b"

[[colors.indexed_colors]]
index = 19
color = "0x5c5653"

[[colors.indexed_colors]]
index = 20
color = "0x8d8782"

[[colors.indexed_colors]]
index = 21
color = "0xbfb9b2"
