# base16 ww7-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x1c2548'
foreground = '0xa5adb8'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1c2548'
cursor = '0xa5adb8'

# Normal colors
[colors.normal]
black = '0x1c2548'
red = '0xe1211b'
green = '0x2c9c69'
yellow = '0xe2a947'
blue = '0x0927c3'
magenta = '0x553c56'
cyan = '0x1bbcb6'
#white = '0xa5adb8'
white = '0xdde4e6'

# Bright colors
[colors.bright]
black = '0x6e768b'
red = '0xe1211b'
green = '0x2c9c69'
yellow = '0xe2a947'
blue = '0x0927c3'
magenta = '0x553c56'
cyan = '0x1bbcb6'
white = '0xdde4e6'

[[colors.indexed_colors]]
index = 16
color = "0xe88e3f"

[[colors.indexed_colors]]
index = 17
color = "0x7d626e"

[[colors.indexed_colors]]
index = 18
color = "0x37405e"

[[colors.indexed_colors]]
index = 19
color = "0x535b75"

[[colors.indexed_colors]]
index = 20
color = "0x8a92a2"

[[colors.indexed_colors]]
index = 21
color = "0xc1c8cf"
