# base16 adaptive-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x1d292c'
foreground = '0x8d9a9e'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1d292c'
cursor = '0x8d9a9e'

# Normal colors
[colors.normal]
black = '0x1d292c'
red = '0xc3767d'
green = '0x006756'
yellow = '0xd5988d'
blue = '0x2a6772'
magenta = '0xc3767d'
cyan = '0x3c8982'
#white = '0x8d9a9e'
white = '0xbac8cc'

# Bright colors
[colors.bright]
black = '0x606d70'
red = '0xc3767d'
green = '0x006756'
yellow = '0xd5988d'
blue = '0x2a6772'
magenta = '0xc3767d'
cyan = '0x3c8982'
white = '0xbac8cc'

[[colors.indexed_colors]]
index = 16
color = "0xd58283"

[[colors.indexed_colors]]
index = 17
color = "0x422f43"

[[colors.indexed_colors]]
index = 18
color = "0x333f42"

[[colors.indexed_colors]]
index = 19
color = "0x495659"

[[colors.indexed_colors]]
index = 20
color = "0x768387"

[[colors.indexed_colors]]
index = 21
color = "0xa3b1b5"
