# base16 77-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x391f28'
foreground = '0xb0aba7'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x391f28'
cursor = '0xb0aba7'

# Normal colors
[colors.normal]
black = '0x391f28'
red = '0x9d4c2e'
green = '0x4f7f54'
yellow = '0xeea760'
blue = '0x11589f'
magenta = '0x583581'
cyan = '0x19eff7'
#white = '0xb0aba7'
white = '0xe0e4da'

# Bright colors
[colors.bright]
black = '0x807374'
red = '0x9d4c2e'
green = '0x4f7f54'
yellow = '0xeea760'
blue = '0x11589f'
magenta = '0x583581'
cyan = '0x19eff7'
white = '0xe0e4da'

[[colors.indexed_colors]]
index = 16
color = "0xd58f4b"

[[colors.indexed_colors]]
index = 17
color = "0x744555"

[[colors.indexed_colors]]
index = 18
color = "0x503b41"

[[colors.indexed_colors]]
index = 19
color = "0x68575a"

[[colors.indexed_colors]]
index = 20
color = "0x988f8d"

[[colors.indexed_colors]]
index = 21
color = "0xc8c7c0"
