# base16 103-result-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x2e2235'
foreground = '0xa69cab'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2e2235'
cursor = '0xa69cab'

# Normal colors
[colors.normal]
black = '0x2e2235'
red = '0x605443'
green = '0x14a64b'
yellow = '0xde8d66'
blue = '0x217299'
magenta = '0x5e486a'
cyan = '0x1af9ce'
#white = '0xa69cab'
white = '0xd7cedb'

# Bright colors
[colors.bright]
black = '0x766b7c'
red = '0x605443'
green = '0x14a64b'
yellow = '0xde8d66'
blue = '0x217299'
magenta = '0x5e486a'
cyan = '0x1af9ce'
white = '0xd7cedb'

[[colors.indexed_colors]]
index = 16
color = "0xcb7350"

[[colors.indexed_colors]]
index = 17
color = "0x66193e"

[[colors.indexed_colors]]
index = 18
color = "0x463a4c"

[[colors.indexed_colors]]
index = 19
color = "0x5e5364"

[[colors.indexed_colors]]
index = 20
color = "0x8e8493"

[[colors.indexed_colors]]
index = 21
color = "0xbeb5c3"
