# base16 fishpool-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x2d261a'
foreground = '0xb1b3ab'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2d261a'
cursor = '0xb1b3ab'

# Normal colors
[colors.normal]
black = '0x2d261a'
red = '0x866879'
green = '0x067e72'
yellow = '0xc99e8c'
blue = '0x457c93'
magenta = '0x7b6297'
cyan = '0x43fcee'
#white = '0xb1b3ab'
white = '0xe7ece6'

# Bright colors
[colors.bright]
black = '0x7c7a71'
red = '0x866879'
green = '0x067e72'
yellow = '0xc99e8c'
blue = '0x457c93'
magenta = '0x7b6297'
cyan = '0x43fcee'
white = '0xe7ece6'

[[colors.indexed_colors]]
index = 16
color = "0xe26164"

[[colors.indexed_colors]]
index = 17
color = "0x8f5144"

[[colors.indexed_colors]]
index = 18
color = "0x474237"

[[colors.indexed_colors]]
index = 19
color = "0x625e54"

[[colors.indexed_colors]]
index = 20
color = "0x97978e"

[[colors.indexed_colors]]
index = 21
color = "0xcccfc8"
