# base16 vlcsnap-2024-10-01-04h34m38s154-png 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x25253a'
foreground = '0x9f9d9a'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x25253a'
cursor = '0x9f9d9a'

# Normal colors
[colors.normal]
black = '0x25253a'
red = '0xc72b0d'
green = '0x479b3c'
yellow = '0xbdad67'
blue = '0x1335d6'
magenta = '0x424162'
cyan = '0x33a6da'
#white = '0x9f9d9a'
white = '0xd1cec1'

# Bright colors
[colors.bright]
black = '0x6e6d73'
red = '0xc72b0d'
green = '0x479b3c'
yellow = '0xbdad67'
blue = '0x1335d6'
magenta = '0x424162'
cyan = '0x33a6da'
white = '0xd1cec1'

[[colors.indexed_colors]]
index = 16
color = "0xe4a65c"

[[colors.indexed_colors]]
index = 17
color = "0x904b5b"

[[colors.indexed_colors]]
index = 18
color = "0x3d3d4d"

[[colors.indexed_colors]]
index = 19
color = "0x565560"

[[colors.indexed_colors]]
index = 20
color = "0x878587"

[[colors.indexed_colors]]
index = 21
color = "0xb8b5ad"
