# base16 wallhaven-yxdvjx-png 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x222915'
foreground = '0x9fa8a4'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x222915'
cursor = '0x9fa8a4'

# Normal colors
[colors.normal]
black = '0x222915'
red = '0xc30700'
green = '0x38ad22'
yellow = '0xf9d906'
blue = '0x0a15e0'
magenta = '0x80007e'
cyan = '0x32a3cf'
#white = '0x9fa8a4'
white = '0xd2dbde'

# Bright colors
[colors.bright]
black = '0x6d756b'
red = '0xc30700'
green = '0x38ad22'
yellow = '0xf9d906'
blue = '0x0a15e0'
magenta = '0x80007e'
cyan = '0x32a3cf'
white = '0xd2dbde'

[[colors.indexed_colors]]
index = 16
color = "0xffa30f"

[[colors.indexed_colors]]
index = 17
color = "0xa62928"

[[colors.indexed_colors]]
index = 18
color = "0x3b4231"

[[colors.indexed_colors]]
index = 19
color = "0x545b4e"

[[colors.indexed_colors]]
index = 20
color = "0x868e87"

[[colors.indexed_colors]]
index = 21
color = "0xb8c1c1"
