# base16 9uPsXc8-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x1d2830'
foreground = '0x97988e'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1d2830'
cursor = '0x97988e'

# Normal colors
[colors.normal]
black = '0x1d2830'
red = '0xaa4a45'
green = '0x778f44'
yellow = '0xc0ad6b'
blue = '0x455aa3'
magenta = '0x96516e'
cyan = '0x5cb8bc'
#white = '0x97988e'
white = '0xc8c5b4'

# Bright colors
[colors.bright]
black = '0x666b68'
red = '0xaa4a45'
green = '0x778f44'
yellow = '0xc0ad6b'
blue = '0x455aa3'
magenta = '0x96516e'
cyan = '0x5cb8bc'
white = '0xc8c5b4'

[[colors.indexed_colors]]
index = 16
color = "0xad8040"

[[colors.indexed_colors]]
index = 17
color = "0x897f6c"

[[colors.indexed_colors]]
index = 18
color = "0x353e42"

[[colors.indexed_colors]]
index = 19
color = "0x4d5455"

[[colors.indexed_colors]]
index = 20
color = "0x7e817b"

[[colors.indexed_colors]]
index = 21
color = "0xafaea1"
