# base16 bird-png 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x2c261e'
foreground = '0xbcbab6'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2c261e'
cursor = '0xbcbab6'

# Normal colors
[colors.normal]
black = '0x2c261e'
red = '0xa04d20'
green = '0x325266'
yellow = '0xe1c355'
blue = '0x1e3caa'
magenta = '0x764d36'
cyan = '0x5fb2df'
#white = '0xbcbab6'
white = '0xf6f6f4'

# Bright colors
[colors.bright]
black = '0x827f79'
red = '0xa04d20'
green = '0x325266'
yellow = '0xe1c355'
blue = '0x1e3caa'
magenta = '0x764d36'
cyan = '0x5fb2df'
white = '0xf6f6f4'

[[colors.indexed_colors]]
index = 16
color = "0x62809a"

[[colors.indexed_colors]]
index = 17
color = "0x975c34"

[[colors.indexed_colors]]
index = 18
color = "0x48433c"

[[colors.indexed_colors]]
index = 19
color = "0x65615b"

[[colors.indexed_colors]]
index = 20
color = "0x9f9c98"

[[colors.indexed_colors]]
index = 21
color = "0xd9d8d5"
