# base16 rubik-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x1a273f'
foreground = '0x9e9b9e'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1a273f'
cursor = '0x9e9b9e'

# Normal colors
[colors.normal]
black = '0x1a273f'
red = '0xff0000'
green = '0x2fcb6a'
yellow = '0xdab83b'
blue = '0x0b27e8'
magenta = '0x812781'
cyan = '0x3cd4bf'
#white = '0x9e9b9e'
white = '0xd4cac4'

# Bright colors
[colors.bright]
black = '0x696c78'
red = '0xff0000'
green = '0x2fcb6a'
yellow = '0xdab83b'
blue = '0x0b27e8'
magenta = '0x812781'
cyan = '0x3cd4bf'
white = '0xd4cac4'

[[colors.indexed_colors]]
index = 16
color = "0xd88c30"

[[colors.indexed_colors]]
index = 17
color = "0xa74758"

[[colors.indexed_colors]]
index = 18
color = "0x343e52"

[[colors.indexed_colors]]
index = 19
color = "0x4f5565"

[[colors.indexed_colors]]
index = 20
color = "0x84848b"

[[colors.indexed_colors]]
index = 21
color = "0xb9b2b1"
