# base16 dimitri-jakubowski-foxy-girl-blue-illu-forest-artstation-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x17235c'
foreground = '0x9da5b9'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x17235c'
cursor = '0x9da5b9'

# Normal colors
[colors.normal]
black = '0x17235c'
red = '0xcf0818'
green = '0x00ff00'
yellow = '0xf9fc00'
blue = '0x0911d6'
magenta = '0x5b0f3d'
cyan = '0x00feff'
#white = '0x9da5b9'
white = '0xd3d9df'

# Bright colors
[colors.bright]
black = '0x677194'
red = '0xcf0818'
green = '0x00ff00'
yellow = '0xf9fc00'
blue = '0x0911d6'
magenta = '0x5b0f3d'
cyan = '0x00feff'
white = '0xd3d9df'

[[colors.indexed_colors]]
index = 16
color = "0xffa400"

[[colors.indexed_colors]]
index = 17
color = "0xa72828"

[[colors.indexed_colors]]
index = 18
color = "0x313d6e"

[[colors.indexed_colors]]
index = 19
color = "0x4c5781"

[[colors.indexed_colors]]
index = 20
color = "0x828ba6"

[[colors.indexed_colors]]
index = 21
color = "0xb8bfcc"
