# base16 9-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x272726'
foreground = '0xa6adab'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x272726'
cursor = '0xa6adab'

# Normal colors
[colors.normal]
black = '0x272726'
red = '0x9e342d'
green = '0x407655'
yellow = '0xeaa969'
blue = '0x155696'
magenta = '0x5f276d'
cyan = '0x61cbd2'
#white = '0xa6adab'
white = '0xdae3e1'

# Bright colors
[colors.bright]
black = '0x737776'
red = '0x9e342d'
green = '0x407655'
yellow = '0xeaa969'
blue = '0x155696'
magenta = '0x5f276d'
cyan = '0x61cbd2'
white = '0xdae3e1'

[[colors.indexed_colors]]
index = 16
color = "0xe1875a"

[[colors.indexed_colors]]
index = 17
color = "0x937059"

[[colors.indexed_colors]]
index = 18
color = "0x404140"

[[colors.indexed_colors]]
index = 19
color = "0x5a5c5b"

[[colors.indexed_colors]]
index = 20
color = "0x8d9290"

[[colors.indexed_colors]]
index = 21
color = "0xc0c8c6"
