# base16 Background-jpg 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x0c2031'
foreground = '0x8e978d'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x0c2031'
cursor = '0x8e978d'

# Normal colors
[colors.normal]
black = '0x0c2031'
red = '0xff0001'
green = '0x00ac67'
yellow = '0xffb568'
blue = '0x0100b2'
magenta = '0x71285d'
cyan = '0x6f7e9d'
#white = '0x8e978d'
white = '0xc2c7b3'

# Bright colors
[colors.bright]
black = '0x5a6768'
red = '0xff0001'
green = '0x00ac67'
yellow = '0xffb568'
blue = '0x0100b2'
magenta = '0x71285d'
cyan = '0x6f7e9d'
white = '0xc2c7b3'

[[colors.indexed_colors]]
index = 16
color = "0xe87e43"

[[colors.indexed_colors]]
index = 17
color = "0x953536"

[[colors.indexed_colors]]
index = 18
color = "0x263743"

[[colors.indexed_colors]]
index = 19
color = "0x404f56"

[[colors.indexed_colors]]
index = 20
color = "0x747f7b"

[[colors.indexed_colors]]
index = 21
color = "0xa8afa0"
