# base16 horizon_by_aenami_dd7ziro-png 256 - alacritty color config
# Tinty

# Default colors
[colors.primary]
background = '0x1f243d'
foreground = '0xa7a9a8'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1f243d'
cursor = '0xa7a9a8'

# Normal colors
[colors.normal]
black = '0x1f243d'
red = '0xb1433c'
green = '0x179d8b'
yellow = '0xd4b65b'
blue = '0x101dc5'
magenta = '0x544d66'
cyan = '0x4ebcc3'
#white = '0xa7a9a8'
white = '0xdedfd4'

# Bright colors
[colors.bright]
black = '0x70747d'
red = '0xb1433c'
green = '0x179d8b'
yellow = '0xd4b65b'
blue = '0x101dc5'
magenta = '0x544d66'
cyan = '0x4ebcc3'
white = '0xdedfd4'

[[colors.indexed_colors]]
index = 16
color = "0xcea355"

[[colors.indexed_colors]]
index = 17
color = "0xb64c4d"

[[colors.indexed_colors]]
index = 18
color = "0x3a3e52"

[[colors.indexed_colors]]
index = 19
color = "0x555968"

[[colors.indexed_colors]]
index = 20
color = "0x8c8e93"

[[colors.indexed_colors]]
index = 21
color = "0xc2c4be"
