# Flatpak

add = "flatpak install --user #:?"
remove = "flatpak uninstall --force-remove --no-related #:?"
upgrade = "flatpak update"

plural_name = "flatpaks"

hook_name = "flatpaks"

[config]
many_args = true
