shell = "bash -c '{}'"

[[item]]
    file = '~/.config/swaylock/config'
    template = 'swaylock'
    rewrite = false
    start = "# TINTY START"
    end = "# TINTY END"


[[item]]
    file = '~/.config/satty/config.toml'
    template = 'satty'
    rewrite = false
    start = "### Here starts flavours injection"
    end = "### Here ends flavours injection"

[[item]]
    file = '~/.config/starship.toml'
    template = 'starship'
    rewrite = false
    start = "# TINTY START"
    end = "# TINTY END"

# [[item]]
#     file = '~/.local/share/themes/FlatColor/colors2'
#     template = 'gtk-flatcolor'
#     subtemplate = 'gtk-2'
#     rewrite = true

# [[item]]
#     file = '~/.local/share/themes/FlatColor/colors3'
#     template = 'gtk-flatcolor'
#     subtemplate = 'gtk-3'
#     rewrite = true
#     hook = 'gsettings set org.gnome.desktop.interface gtk-theme dummy && gsettings set org.gnome.desktop.interface gtk-theme FlatColor'
