#!/usr/bin/env bash

CFG="$HOME/.config/eww/exmpl"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} --config "$CFG"  --force-wayland daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" open bar
}

## Launch or close widgets accordingly
run_eww
